project:
  type: website

website:
  title: "TUHH Institute of Entrepreneurship"
  favicon: assets/images/icon.svg
  navbar:
    logo: "assets/images/logo.svg"
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
  
  
editor: visual

