project:
  type: website
  render:
    - "*.qmd"
    - "!z_current_website/"
    - "!z_TUHH_styles/"

website:
  title: "TUHH Institute of Entrepreneurship"
  favicon: assets/images/icon.svg
  open-graph:
    locale: de_DE
    site-name: TUHH Institute of Entrepreneurship
  page-navigation: false
  back-to-top-navigation: true
  # bread-crumbs: true 

  search:
    location: navbar # vs sidebar
    type: overlay
  
  
  navbar:
    title: false
    pinned: true
    toggle-position: right # stable only in the next version
    foreground: "$text_blue"
    # background: "white"
    logo: assets/images/logo.svg
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Welcome
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: transfer.qmd
        text: Transfer
      - href: contact.qmd
        text: Contact
      # - icon: envelope
      #   href: "mailto:startup.engineer@tuhh.de"

      
  page-footer:
    left: |
      [![](/assets/images/logo_tuhh_full.svg){fig-alt="TU Hamburg" width=145px}](https://www.tuhh.de/)
    right: |
      <span class='footer-address'>
      <span style='letter-spacing: 4px; text-transform: uppercase; font-weight: 400; font-size: 13px; line-height: 1.55;'>TU Hamburg</span><br><br>
      <span style='font-weight: 400; font-size: 14px; line-height: 1.8;'>Institut für Thermische Verfahrenstechnik<br>
      Eißendorfer Straße 38 (O)<br>
      21073 Hamburg</span>
      <br><br>
      <span style='font-weight: 400; font-size: 14px; line-height: 1.8;'>E-Mail : secretary.tvt[at]tuhh[dot]de<br>
      Tel : +49 40 42878 3240</span>
      </span>
      <span class='footer-social'>
      <span style='letter-spacing: 4px; text-transform: uppercase; font-weight: 400; font-size: 13px; line-height: 1.55;'>Soziale Netzwerke</span><br><br>
      <span style='font-weight: 400; font-size: 20px; line-height: 1.55;'>
      [{{< fa brands linkedin >}}](https://www.linkedin.com/in/institute-for-thermal-separation-processes-700282293/)
      </span>
      </span>
      <span class='footer-ql-left'>
      <span style='letter-spacing: 4px; text-transform: uppercase; font-weight: 400; font-size: 13px; line-height: 1.55;'>Weiterführende Links</span><br><br>
      ![](/assets/images/link.svg){height=1em}&nbsp;&nbsp;&nbsp;[Data Privacy](/privacy.qmd)<br><br>
      ![](/assets/images/link.svg){height=1em}&nbsp;&nbsp;&nbsp;[Imprint](/imprint.qmd)
      </span>
      <span class='footer-ql-right'>
      ![](/assets/images/link.svg){height=1em}&nbsp;&nbsp;&nbsp;[Contact / Map](/contact.qmd)
      </span>
    background: $footer_blue
    foreground: "white"
    
  # sidebar:
    # style: "floating"
    # search: true
    # contents: auto

format:
  html:
    toc: true
    theme:
      light: theme/custom.scss
      dark: [theme/custom.scss, theme/custom_dark.scss]
    # css: theme/styles.css
    code-copy: true
    code-overflow: wrap
    mainfont: PublicaSans # PublicaSans ; Poppins
    grid:
      sidebar-width: 0px
      body-width: $page_width
      margin-width: 0px



execute:
  freeze: auto
  
  
editor: visual

