project:
  type: website
  render:
    - "*.qmd"
    - "!z_current_website/"
    - "!z_TUHH_styles/"

website:
  title: "TUHH Institute of Entrepreneurship"
  site-url: https://www.startupengineer.io
  favicon: assets/images/icon.svg
  open-graph:
    locale: de_DE
    site-name: TUHH Institute of Entrepreneurship
    image: assets/images/docks.jpg
  twitter-card:
    image: assets/images/docks.jpg
  page-navigation: false
  back-to-top-navigation: true
  # bread-crumbs: true 

  search:
    location: navbar # vs sidebar
    type: overlay
  
  
  navbar:
    title: false
    pinned: true
    toggle-position: right # stable only in the next version
    foreground: "$text_blue"
    # background: "white"
    logo: assets/images/logo.svg
    logo-href: /
    left:
      - href: index.qmd
        text: Welcome
      - href: news.qmd
        text: News
      - text: Team
        menu:
          - text: Team
            href: team.qmd#sec-current-team
          - text: Alumni
            href: team.qmd#sec-alumni
          - text: Gallery
            href: team.qmd#gallery
      - text: Research
        menu:
          - text: Focus
            href: research.qmd#sec-focus-fields
          - text: Projects
            href: research.qmd#sec-projects
          - text: Publications
            href: research.qmd#sec-publications
      - text: Teaching
        menu:
          - text: Current Courses
            href: teaching.qmd#sec-current-courses
          - text: Upcoming Courses
            href: teaching.qmd#sec-upcoming-courses
          - text: Open Theses
            href: teaching.qmd#sec-open-theses
      - href: collab.qmd
        text: Collaborate
      # - icon: envelope
      #   href: "mailto:startup.engineer@tuhh.de"

      
  page-footer:
    left: |
      [![](/assets/images/logo_tuhh_full.svg){fig-alt="TU Hamburg" width=145px}](https://www.tuhh.de/)
    right: |
      <span class='footer-address'>
      <span class='footer-col-heading'>TU Hamburg</span><br><br>
      <span class='footer-col-body'>TUHH Institute of Entrepreneurship<br>
      Prof. Dr. Christoph Ihl<br>
      Am Irrgarten 3<br>
      21073 Hamburg</span>
      </span>
      <span class='footer-social'>
      <span class='footer-col-heading'>Contact</span><br><br>
      <span class='footer-col-body'>
      {{< fa envelope >}} : &nbsp;&nbsp;[startup.engineer@tuhh.de](mailto:startup.engineer@tuhh.de)<br>
      {{< fa phone >}} : &nbsp;&nbsp;+49 (0)40 42878-3226<br>
      {{< fa brands linkedin >}} : &nbsp;&nbsp;[LinkedIn](https://www.linkedin.com/company/tuhh-institute-of-entrepreneurship)<br>
      {{< fa location-dot >}} : &nbsp;&nbsp;[Directions](https://www.openstreetmap.org/search?query=Am+Irrgarten+3%2C+21073+Hamburg)
      </span>
      </span>
      <span class='footer-ql-heading'>
      <span style='letter-spacing: 4px; text-transform: uppercase; font-weight: 400; font-size: 13px; line-height: 1.55;'>Links</span>
      </span>
      <span class='footer-ql-left'>
      ![](/assets/images/link.svg){height=1em}&nbsp;&nbsp;&nbsp;[Data Privacy](/privacy.qmd)<br><br>
      ![](/assets/images/link.svg){height=1em}&nbsp;&nbsp;&nbsp;[Imprint](/imprint.qmd)
      </span>
      <span class='footer-ql-right'>
      <span style='font-weight: 400; font-size: 14px; line-height: 1.8;'>Built with [![](/assets/images/quarto.png){height=1.2em}](https://quarto.org/) at [{{< fa brands github >}}](https://github.com/christophihl/TIE_website)</span>
      </span>
    background: $footer_blue
    foreground: "white"
    
  # sidebar:
    # style: "floating"
    # search: true
    # contents: auto

format:
  html:
    toc: true
    include-after-body:
      - theme/nav-dropdown.html
    theme:
      light: theme/custom.scss
      dark: [theme/custom.scss, theme/custom_dark.scss]
    # css: theme/styles.css
    code-copy: true
    code-overflow: wrap
    mainfont: PublicaSans # PublicaSans ; Poppins
    grid:
      sidebar-width: 0px
      body-width: $page_width
      margin-width: 0px



execute:
  freeze: auto
  
  
editor: visual

