{
    "custom-styles": {
        "INI Files": {
            "Section": {
                "selected-text-color": "#7200FE",
                "text-color": "#7200FE"
            }
        },
        "Python": {
            "Builtin Function": {
                "selected-text-color": "#7200FE",
                "text-color": "#7200FE"
            },
            "Import": {
                "selected-text-color": "#FFAEA2",
                "text-color": "#FFAEA2"
            },
            "Special Variable": {
                "selected-text-color": "#143BFF",
                "text-color": "#143BFF"
            }
        },
        "Rust": {
            "Attribute": {
                "selected-text-color": "#e1e4e8",
                "text-color": "#e1e4e8"
            },
            "Macro": {
                "selected-text-color": "#143BFF",
                "text-color": "#143BFF"
            },
            "Self": {
                "selected-text-color": "#143BFF",
                "text-color": "#143BFF"
            },
            "Trait": {
                "selected-text-color": "#e1e4e8",
                "text-color": "#e1e4e8"
            }
        },
        "XML": {
            "Element": {
                "selected-text-color": "#5AFFC5",
                "text-color": "#5AFFC5"
            }
        }
    },
    "background-color": "#005e73",
    "editor-colors": {
        "BackgroundColor": "#005e73",
        "BracketMatching": "#65676a",
        "CodeFolding": "#253749",
        "CurrentLine": "#2b3036",
        "CurrentLineNumber": "#e1e4e8",
        "IconBorder": "#24292e",
        "IndentationLine": "#d7dbe0",
        "LineNumbers": "#444d56",
        "MarkBookmark": "#8be9fd",
        "MarkBreakpointActive": "#FF4F4F",
        "MarkBreakpointDisabled": "#bd93f9",
        "MarkBreakpointReached": "#f1fa8c",
        "MarkError": "#b31d28",
        "MarkExecution": "#44475a",
        "MarkWarning": "#FFDE36",
        "ModifiedLines": "#FFAEA2",
        "ReplaceHighlight": "#40c661",
        "SavedLines": "#28a745",
        "SearchHighlight": "#404030",
        "Separator": "#1b1f23",
        "SpellChecking": "#FF4F4F",
        "TabMarker": "#444d56",
        "TemplateBackground": "#23241e",
        "TemplateFocusedPlaceholder": "#22231d",
        "TemplatePlaceholder": "#22231d",
        "TemplateReadOnlyPlaceholder": "#262721",
        "TextSelection": "#253749",
        "WordWrapMarker": "#2f3031"
    },
    "metadata": {
        "copyright": [
            "SPDX-FileCopyrightText: 2020 GitHub Inc.",
            "SPDX-FileCopyrightText: 2020 Waqar Ahmed <waqar.17a@gmail.com>"
        ],
        "license": "SPDX-License-Identifier: MIT",
        "name": "TIE Dark",
        "revision": 2
    },
    "text-styles": {
        "Alert": {
            "bold": true,
            "selected-text-color": "#FF4F4F",
            "text-color": "#FF4F4F"
        },
        "Annotation": {
            "selected-text-color": "#6a737d",
            "text-color": "#6a737d"
        },
        "Attribute": {
            "selected-text-color": "#FF7E15",
            "text-color": "#FF7E15"
        },
        "BaseN": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "BuiltIn": {
            "selected-text-color": "#FF7E15",
            "text-color": "#FF7E15"
        },
        "Char": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "Comment": {
            "selected-text-color": "#A8968C",
            "text-color": "#A8968C"
        },
        "CommentVar": {
            "selected-text-color": "#A8968C",
            "text-color": "#A8968C"
        },
        "Constant": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "ControlFlow": {
            "selected-text-color": "#FF7E15",
            "text-color": "#FF7E15"
        },
        "DataType": {
            "selected-text-color": "#FFAEA2",
            "text-color": "#FFAEA2"
        },
        "DecVal": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "Documentation": {
            "selected-text-color": "#6a737d",
            "text-color": "#6a737d"
        },
        "Error": {
            "selected-text-color": "#FF4F4F",
            "text-color": "#FF4F4F",
            "underline": true
        },
        "Extension": {
            "bold": true,
            "selected-text-color": "#FFAEA2",
            "text-color": "#FFAEA2"
        },
        "Float": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "Function": {
            "selected-text-color": "#00C1D4",
            "text-color": "#00C1D4"
        },
        "Import": {
            "selected-text-color": "#D0D0CE",
            "text-color": "#D0D0CE"
        },
        "Information": {
            "selected-text-color": "#6a737d",
            "text-color": "#6a737d"
        },
        "Keyword": {
            "selected-text-color": "#FFAEA2",
            "text-color": "#FFAEA2"
        },
        "Normal": {
            "selected-text-color": "#e1e4e8",
            "text-color": "#e1e4e8"
        },
        "Operator": {
            "selected-text-color": "#e1e4e8",
            "text-color": "#e1e4e8"
        },
        "Others": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "Preprocessor": {
            "selected-text-color": "#FFAEA2",
            "text-color": "#FFAEA2"
        },
        "RegionMarker": {
            "selected-text-color": "#6a737d",
            "text-color": "#6a737d"
        },
        "SpecialChar": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "SpecialString": {
            "selected-text-color": "#D0D0CE",
            "text-color": "#D0D0CE"
        },
        "String": {
            "selected-text-color": "#5AFFC5",
            "text-color": "#5AFFC5"
        },
        "Variable": {
            "selected-text-color": "#FFDE36",
            "text-color": "#FFDE36"
        },
        "VerbatimString": {
            "selected-text-color": "#D0D0CE",
            "text-color": "#D0D0CE"
        },
        "Warning": {
            "selected-text-color": "#FF4F4F",
            "text-color": "#FF4F4F"
        }
    }
}
